name: 'Zip Apps'
on:
  push:
    branches:
      - main
  schedule:
    # Run every 24 hours at midnight UTC
    - cron: '0 0 * * *' 

jobs:
  zip_user_folder:
    name: 'Zip USER Directory'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.13.1'

      - name: Zip USER Directory
        run: |
          mkdir -p artifacts
          zip -r artifacts/apps.zip USER

      - name: Upload Zip
        uses: actions/upload-artifact@v4
        with:
          name: apps
          path: artifacts/apps.zip
          retention-days: 7
